### ISSUE TITLE
Is it possible that this works only on Windows?

### ISSUE THREAD

**Issue by karmatikde** [MariyaSha/ml_gui_app#2]
I am on Mac trying to install the packages listed in the **requirements.txt**. If I understand correctly, the following packages are only available for Windows.
**pywin32==306
pywinpty==2.0.12
tensorflow-intel==2.14.0
twisted-iocpsupport==1.0.4**

Is there a workaround for Mac users?

**Comment by MariyaSha** [comment]
Sure! Disregard the requirements file, and just follow these steps:

- create a new working environment
- install Python in it (3.11 in my case, but I don't think it really matters)
- install taipy
- install tensorflow
- install pillow
- install matplotlib 
- install numpy
- install jupyter notebook

And you're good to go ;)
I hope it helps!

**Comment by karmatikde** [comment]
Thank you very much for the quick reply! will give it a try.

**Comment by karmatikde** [comment]
Hi @MariyaSha It worked like a charm. I really struggled with my IDE (pyCharm CE 2023.2.5) with this import: 
`import from tensorflow.keras import models`
Seems like it is a known issue which is discussed [here](https://stackoverflow.com/questions/47262955/how-to-import-keras-from-tf-keras-in-tensorflow). But after I switched to Brackets it worked without any issues. Thank you for yet another awesome tutorial!
